# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(298, 310)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxFunctions = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxFunctions.setGeometry(QtCore.QRect(10, 20, 281, 211))
        self.groupBoxFunctions.setObjectName("groupBoxFunctions")
        self.btnViewReservs = QtWidgets.QPushButton(parent=self.groupBoxFunctions)
        self.btnViewReservs.setGeometry(QtCore.QRect(60, 50, 171, 24))
        self.btnViewReservs.setObjectName("btnViewReservs")
        self.btnNewReserv = QtWidgets.QPushButton(parent=self.groupBoxFunctions)
        self.btnNewReserv.setGeometry(QtCore.QRect(60, 110, 171, 24))
        self.btnNewReserv.setObjectName("btnNewReserv")
        self.btnCancelReserv = QtWidgets.QPushButton(parent=self.groupBoxFunctions)
        self.btnCancelReserv.setGeometry(QtCore.QRect(60, 170, 171, 24))
        self.btnCancelReserv.setObjectName("btnCancelReserv")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(110, 240, 75, 24))
        self.btnExit.setObjectName("btnExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 298, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnViewReservs.clicked.connect(MainWindow.slotViewReservs) # type: ignore
        self.btnNewReserv.clicked.connect(MainWindow.slotCreateReserv) # type: ignore
        self.btnCancelReserv.clicked.connect(MainWindow.slotDeleteReserv) # type: ignore
        self.btnExit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnViewReservs, self.btnNewReserv)
        MainWindow.setTabOrder(self.btnNewReserv, self.btnCancelReserv)
        MainWindow.setTabOrder(self.btnCancelReserv, self.btnExit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Szállodai szobafoglalási rendszer"))
        self.groupBoxFunctions.setTitle(_translate("MainWindow", "Funkciók:"))
        self.btnViewReservs.setText(_translate("MainWindow", "Foglalások megtekintése"))
        self.btnNewReserv.setText(_translate("MainWindow", "Foglalás létrehozása"))
        self.btnCancelReserv.setText(_translate("MainWindow", "Foglalás törlése"))
        self.btnExit.setText(_translate("MainWindow", "Kilép"))
