# Form implementation generated from reading ui file 'reservationAdd.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addReserv(object):
    def setupUi(self, addReserv):
        addReserv.setObjectName("addReserv")
        addReserv.resize(679, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addReserv.sizePolicy().hasHeightForWidth())
        addReserv.setSizePolicy(sizePolicy)
        addReserv.setMinimumSize(QtCore.QSize(679, 480))
        addReserv.setMaximumSize(QtCore.QSize(679, 480))
        self.centralwidget = QtWidgets.QWidget(parent=addReserv)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 671, 271))
        self.calendarWidget.setObjectName("calendarWidget")
        self.btnMakeReserv = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMakeReserv.setGeometry(QtCore.QRect(310, 400, 75, 24))
        self.btnMakeReserv.setObjectName("btnMakeReserv")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 290, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cmbSzobak = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbSzobak.setGeometry(QtCore.QRect(110, 291, 561, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbSzobak.setFont(font)
        self.cmbSzobak.setObjectName("cmbSzobak")
        self.lblGuestName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGuestName.setGeometry(QtCore.QRect(0, 350, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGuestName.setFont(font)
        self.lblGuestName.setObjectName("lblGuestName")
        self.txtGuestName = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.txtGuestName.setGeometry(QtCore.QRect(110, 340, 561, 31))
        self.txtGuestName.setObjectName("txtGuestName")
        addReserv.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=addReserv)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 22))
        self.menubar.setObjectName("menubar")
        addReserv.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=addReserv)
        self.statusbar.setObjectName("statusbar")
        addReserv.setStatusBar(self.statusbar)

        self.retranslateUi(addReserv)
        self.btnMakeReserv.clicked.connect(addReserv.btnClick) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addReserv)

    def retranslateUi(self, addReserv):
        _translate = QtCore.QCoreApplication.translate
        addReserv.setWindowTitle(_translate("addReserv", "Foglalás hozzáadása"))
        self.btnMakeReserv.setText(_translate("addReserv", "Foglalás"))
        self.label.setText(_translate("addReserv", "Válassz szobát:"))
        self.lblGuestName.setText(_translate("addReserv", "Vendég neve:"))
