# Form implementation generated from reading ui file 'ReservationCancel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReservCancel(object):
    def setupUi(self, ReservCancel):
        ReservCancel.setObjectName("ReservCancel")
        ReservCancel.resize(473, 600)
        self.centralwidget = QtWidgets.QWidget(parent=ReservCancel)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 20, 471, 491))
        self.listWidget.setObjectName("listWidget")
        self.btnReservCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnReservCancel.setGeometry(QtCore.QRect(190, 520, 75, 24))
        self.btnReservCancel.setObjectName("btnReservCancel")
        ReservCancel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ReservCancel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 473, 22))
        self.menubar.setObjectName("menubar")
        ReservCancel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ReservCancel)
        self.statusbar.setObjectName("statusbar")
        ReservCancel.setStatusBar(self.statusbar)

        self.retranslateUi(ReservCancel)
        self.btnReservCancel.clicked.connect(ReservCancel.slotCancelReserv) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ReservCancel)

    def retranslateUi(self, ReservCancel):
        _translate = QtCore.QCoreApplication.translate
        ReservCancel.setWindowTitle(_translate("ReservCancel", "Foglalás lemondás"))
        self.btnReservCancel.setText(_translate("ReservCancel", "Lemondás!"))
