# Form implementation generated from reading ui file 'reservationListWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_reservListWindow(object):
    def setupUi(self, reservListWindow):
        reservListWindow.setObjectName("reservListWindow")
        reservListWindow.resize(746, 380)
        self.centralwidget = QtWidgets.QWidget(parent=reservListWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 721, 291))
        self.listWidget.setObjectName("listWidget")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(330, 310, 75, 24))
        self.btnExit.setObjectName("btnExit")
        reservListWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=reservListWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 22))
        self.menubar.setObjectName("menubar")
        reservListWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=reservListWindow)
        self.statusbar.setObjectName("statusbar")
        reservListWindow.setStatusBar(self.statusbar)

        self.retranslateUi(reservListWindow)
        self.btnExit.clicked.connect(reservListWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(reservListWindow)

    def retranslateUi(self, reservListWindow):
        _translate = QtCore.QCoreApplication.translate
        reservListWindow.setWindowTitle(_translate("reservListWindow", "Foglalások listázása"))
        self.btnExit.setText(_translate("reservListWindow", "Kilép"))
